name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
