name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: cardinalby/git-get-release-action@v1
        id: latest_draft_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          latest: true
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Update Release Title
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          RELEASE_ID: ${{ steps.latest_draft_release.outputs.id }}
          TAG_NAME: ${{ github.ref }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_name: ${{ github.ref_name }}
      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.latest_draft_release.outputs.id }}
